<div class="w3-bar-block">
  <?php 
    echo 
       OdaTags::linkBarItem('coordinador/consolidado', 'Notas', 'book-bookmark')
      .OdaTags::linkBarItem('coordinador/riesgo_academico', 'Riesgo', 'book-bookmark')
      .OdaTags::linkBarItem('coordinador/seguimientosConsolidado', 'Seguimientos', 'book-bookmark')
      .OdaTags::linkBarItem('coordinador/listadoEstudiantes', 'Estudiantes Activos', 'person-circle-check')
      .OdaTags::linkBarItem('coordinador/listadoEstudiantesInactivos', 'Estudiantes Inactivos', 'person-circle-xmark')
      .OdaTags::linkBarItem('coordinador/gestion_registros', 'Registros', 'address-card')
      .OdaTags::linkBarItem('coordinador/historico_notas', 'Hist&oacute;ricos', 'timeline')
      .OdaTags::linkBarItem('coordinador/admisiones', 'Admisiones', 'person-walking-arrow-right')
      .OdaTags::linkBarItem('docen-asignar-carga', 'Asignar Carga', 'gear');
  ?>
</div>